type UserQueries {
  get: User!
}

type UserMutations {
  set(userParam: UserParamSet__Input!): User!
}

input UserParamSet__Input {
  name: String!
}

type User {
  id: ID!
  email: String
  name: String
  avatarUrl: String
}
