type User implements Form__Model {
  group__: User
  
  # id: ID!
  name: String!
  emial: String!
  avatar: String!
  
  new_password: String
  old_password: String

  roles:[UserRole!]!
}

type UserRole {
  role: Int!
  description: String
}