type UserQuery {
  get: User!
}

type UserMutation {
  set(user_param: UserParamSet__Input!): User!
}

input UserParamSet__Input {
  name: String!
}

type User {
  id: ID!
  email: String
  name: String
  avatar_url: String
}
