type User {
  id: ID!
  name: String!
  email: String!
  avatar: String
  password: String!
  
  new_password: String
  old_password: String

  roles:[UserRole!]!
}

type UserRole {
  role: Int!
  description: String
}

extend type User implements IModel{
  model__: User
}

extend type Query {
  user(email: String!): User!
}

input User_Input__param {
  name: String
  email: String!
  password:String!
}